### ISSUE TITLE
alt to images

### ISSUE THREAD

**Issue by j-agathos** [taras-d/images-grid#3]
Hi excellent work, well done!
how can i add alt, title, width and height to images?
is it possible to fetch thumbnail and on-click the large image?

**Comment by taras-d** [comment]
@j-agathos  thanks!

Image alt and title can be set in `images` option (https://github.com/taras-d/images-grid#images-array).
You cannot set image width/height, because width/height computed automatically to make grid look nice.

To fetch thumbnail and click on large image please look at the events section https://github.com/taras-d/images-grid/blob/master/README.md#events.

**Comment by j-agathos** [comment]
thank you very much for your help, and again excellent work
